name: e2e tests

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run Standard FGSM Tests
        run: |
          pytest ./tests/e2e/test_end2end.py::test_perform_attack_standard -v --log-cli-level=INFO

      - name: Run Targeted FGSM Tests
        run: |
          pytest ./tests/e2e/test_end2end.py::test_perform_attack_targeted -v --log-cli-level=INFO
